doctrine:
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: true
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: false
                mappings:
                    Users:
                        type: xml
                        dir: '%kernel.project_dir%/../src/Users/Infrastructure/Persistence/Doctrine/Proxy/Mapping'
                        is_bundle: false
                        prefix: App\Users\Infrastructure\Persistence\Doctrine\Proxy
                        alias: Users
            read:
                connection: read
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: false
                mappings:
                    Users:
                        type: xml
                        dir: '%kernel.project_dir%/../src/Users/Infrastructure/Persistence/Doctrine/Mapping'
                        is_bundle: false
                        prefix: App\Users\Domain\Entity
                        alias: Users