doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
        types:
            projectId: App\Projects\Infrastructure\Persistence\Doctrine\Type\ProjectIdType
            projectStatus: App\Projects\Infrastructure\Persistence\Doctrine\Type\ProjectStatusType
            projectFinishDate: App\Projects\Infrastructure\Persistence\Doctrine\Type\ProjectFinishDateType
            userId: App\Users\Infrastructure\Persistence\Doctrine\Type\UserIdType
            taskId: App\Tasks\Infrastructure\Persistence\Doctrine\Type\TaskIdType
            taskStatus: App\Tasks\Infrastructure\Persistence\Doctrine\Type\TaskStatusType
            taskStartDate: App\Tasks\Infrastructure\Persistence\Doctrine\Type\TaskStartDateType
            taskFinishDate: App\Tasks\Infrastructure\Persistence\Doctrine\Type\TaskFinishDateType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Users:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Users/Infrastructure/Persistence/Doctrine/'
                prefix: 'App\Users\Domain'
                alias: App
            Projects:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Projects/Infrastructure/Persistence/Doctrine/'
                prefix: 'App\Projects\Domain'
                alias: App
            Tasks:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Tasks/Infrastructure/Persistence/Doctrine/'
                prefix: 'App\Tasks\Domain'
                alias: App

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
