x-php-fpm-template: &php-template
    restart: unless-stopped
    working_dir: /var/www
    depends_on:
        - db
        - php-fpm-base
        - rabbitmq
    build: &php-template-build
        context: ./
        dockerfile: ./docker/images/php/Dockerfile
services:
    php-fpm-base:
        container_name: task_manager-php-base
        image: task_manager-php-base
        build:
            context: ./
            dockerfile: ./docker/images/php/Dockerfile-base
        command: "exit 0"
    rabbitmq:
        container_name: task_manager-rabbitmq
        image: 'rabbitmq:3.10.5-management'
        restart: unless-stopped
        ports:
            - "5672:5672"
            - "15672:15672"
    php-fpm-projects:
        <<: *php-template
        container_name: task_manager-php-projects
        build:
            <<: *php-template-build
            args:
                COMMON_NAME: projects
        volumes:
            - ./app/src/Shared:/var/www/src/Shared
            - ./app/symfony:/var/www/symfony
            - ./app/config/shared:/var/www/config/shared
            - ./app/src/Projects:/var/www/src/Projects
            - ./app/config/projects:/var/www/config/app
            - ./logs/supervisor/projects:/var/log/supervisor
        ports:
            - '8080:8080'
    php-fpm-users:
        <<: *php-template
        container_name: task_manager-php-users
        build:
            <<: *php-template-build
            args:
                COMMON_NAME: users
        volumes:
            - ./app/src/Shared:/var/www/src/Shared
            - ./app/symfony:/var/www/symfony
            - ./app/config/shared:/var/www/config/shared
            - ./app/src/Users:/var/www/src/Users
            - ./app/config/users:/var/www/config/app
            - ./logs/supervisor/users:/var/log/supervisor
        ports:
            - '8081:8080'
    php-fpm-requests:
        <<: *php-template
        container_name: task_manager-php-requests
        build:
            <<: *php-template-build
            args:
                COMMON_NAME: requests
        volumes:
            - ./app/src/Shared:/var/www/src/Shared
            - ./app/symfony:/var/www/symfony
            - ./app/config/shared:/var/www/config/shared
            - ./app/src/Requests:/var/www/src/Requests
            - ./app/config/requests:/var/www/config/app
            - ./logs/supervisor/requests:/var/log/supervisor
        ports:
            - '8082:8080'
    php-fpm-tasks:
        <<: *php-template
        container_name: task_manager-php-tasks
        build:
            <<: *php-template-build
            args:
                COMMON_NAME: tasks
        volumes:
            - ./app/src/Shared:/var/www/src/Shared
            - ./app/symfony:/var/www/symfony
            - ./app/config/shared:/var/www/config/shared
            - ./app/src/Tasks:/var/www/src/Tasks
            - ./app/config/tasks:/var/www/config/app
            - ./logs/supervisor/tasks:/var/log/supervisor
        ports:
            - '8083:8080'
    php-fpm-projections:
        <<: *php-template
        container_name: task_manager-php-projections
        build:
            <<: *php-template-build
            args:
                COMMON_NAME: projections
        volumes:
            - ./app/src/Shared:/var/www/src/Shared
            - ./app/symfony:/var/www/symfony
            - ./app/config/shared:/var/www/config/shared
            - ./app/src/Projections:/var/www/src/Projections
            - ./app/config/projections:/var/www/config/app
            - ./logs/supervisor/projections:/var/log/supervisor
    db:
        container_name: task_manager-db
        image: postgres:14.2-alpine3.15
        restart: always
        environment:
            POSTGRES_USER: symfony
            POSTGRES_PASSWORD: symfony
        ports:
            - '5432:5432'
        volumes:
            - ./data/db:/var/lib/postgresql/data
    adminer:
        container_name: task_manager-adminer
        image: adminer:latest
        restart: always
        ports:
            - '9080:8080'