version: '3.8'

services:
    php-fpm-projects:
        container_name: task_manager-php-projects
        build:
            context: ./
            dockerfile: ./docker/images/php/Dockerfile
        restart: unless-stopped
        user: "${UID}:${GID}"
        ports:
            - '8080:8080'
        volumes:
            - ./app/src/Shared:/var/www/src/Shared
            - ./app/src/Projects:/var/www/src/Projects
            - ./app/symfony:/var/www/symfony
            - ./app/config/shared:/var/www/config/shared
            - ./app/config/project:/var/www/config/app
        working_dir: /var/www
        depends_on:
            - db
        command: symfony serve --dir=symfony/public --port=8080
        environment:
            - DATABASE_USER=symfony
            - DATABASE_PASSWORD=symfony
            - DATABASE_HOST=task_manager-db
            - DATABASE_DB=projects
            - APP_CACHE_DIR=projects
            - APP_LOG_DIR=projects
    php-fpm-users:
        container_name: task_manager-php-users
        build:
            context: ./
            dockerfile: ./docker/images/php/Dockerfile
        restart: unless-stopped
        user: "${UID}:${GID}"
        ports:
            - '8081:8081'
        volumes:
            - ./app/src/Shared:/var/www/src/Shared
            - ./app/src/Users:/var/www/src/Users
            - ./app/symfony:/var/www/symfony
            - ./app/config/shared:/var/www/config/shared
            - ./app/config/user:/var/www/config/app
        working_dir: /var/www
        depends_on:
            - db
        command: symfony serve --dir=symfony/public --port=8081
        environment:
            - DATABASE_USER=symfony
            - DATABASE_PASSWORD=symfony
            - DATABASE_HOST=task_manager-db
            - DATABASE_DB=users
            - APP_CACHE_DIR=users
            - APP_LOG_DIR=users
    php-fpm-requests:
        container_name: task_manager-php-requests
        build:
            context: ./
            dockerfile: ./docker/images/php/Dockerfile
        restart: unless-stopped
        user: "${UID}:${GID}"
        ports:
            - '8082:8082'
        volumes:
            - ./app/src/Shared:/var/www/src/Shared
            - ./app/src/Requests:/var/www/src/Requests
            - ./app/symfony:/var/www/symfony
            - ./app/config/shared:/var/www/config/shared
            - ./app/config/request:/var/www/config/app
        working_dir: /var/www
        depends_on:
            - db
        command: symfony serve --dir=symfony/public --port=8082
        environment:
            - DATABASE_USER=symfony
            - DATABASE_PASSWORD=symfony
            - DATABASE_HOST=task_manager-db
            - DATABASE_DB=requests
            - APP_CACHE_DIR=requests
            - APP_LOG_DIR=requests
    php-fpm-tasks:
        container_name: task_manager-php-tasks
        build:
            context: ./
            dockerfile: ./docker/images/php/Dockerfile
        restart: unless-stopped
        user: "${UID}:${GID}"
        ports:
            - '8083:8083'
        volumes:
            - ./app/src/Shared:/var/www/src/Shared
            - ./app/src/Tasks:/var/www/src/Tasks
            - ./app/symfony:/var/www/symfony
            - ./app/config/shared:/var/www/config/shared
            - ./app/config/request:/var/www/config/app
        working_dir: /var/www
        depends_on:
            - db
        command: symfony serve --dir=symfony/public --port=8083
        environment:
            - DATABASE_USER=symfony
            - DATABASE_PASSWORD=symfony
            - DATABASE_HOST=task_manager-db
            - DATABASE_DB=tasks
            - APP_CACHE_DIR=tasks
            - APP_LOG_DIR=tasks
    db:
        container_name: task_manager-db
        image: postgres:14.2-alpine3.15
        restart: always
        environment:
            POSTGRES_USER: symfony
            POSTGRES_PASSWORD: symfony
        ports:
            - '5432:5432'
        volumes: 
            - ./data/db:/var/lib/postgresql/data
            - ./logs/db:/var/log/nginx
    adminer:
        container_name: task_manager-adminer
        image: adminer:latest
        restart: always
        ports:
            - '9080:9080'