version: '3.8'

services:
    php-fpm-base:
        container_name: task_manager-php-base
        image: task_manager-php-base
        build:
            context: ./
            dockerfile: ./docker/images/php/Dockerfile-base
        command: "exit 0"
    rabbitmq:
        container_name: task_manager-rabbitmq
        image: 'rabbitmq:3.10.5-management'
        restart: unless-stopped
        ports:
            - "5672:5672"
            - "15672:15672"
    php-fpm-projects:
        container_name: task_manager-php-projects
        build:
            context: ./
            dockerfile: ./docker/images/php/Dockerfile
            args:
                COMMON_NAME: projects
                HTTP_SERVER_PORT: 8080
        restart: unless-stopped
        ports:
            - '8080:8080'
        volumes:
            - ./app/src/Shared:/var/www/src/Shared
            - ./app/src/Projects:/var/www/src/Projects
            - ./app/symfony:/var/www/symfony
            - ./app/config/shared:/var/www/config/shared
            - ./app/config/project:/var/www/config/app
        working_dir: /var/www
        depends_on:
            - db
            - php-fpm-base
            - rabbitmq
    php-fpm-users:
        container_name: task_manager-php-users
        build:
            context: ./
            dockerfile: ./docker/images/php/Dockerfile
            args:
                COMMON_NAME: users
                HTTP_SERVER_PORT: 8081
        restart: unless-stopped
        ports:
            - '8081:8081'
        volumes:
            - ./app/src/Shared:/var/www/src/Shared
            - ./app/src/Users:/var/www/src/Users
            - ./app/symfony:/var/www/symfony
            - ./app/config/shared:/var/www/config/shared
            - ./app/config/user:/var/www/config/app
        working_dir: /var/www
        depends_on:
            - db
            - php-fpm-base
            - rabbitmq
    php-fpm-requests:
        container_name: task_manager-php-requests
        build:
            context: ./
            dockerfile: ./docker/images/php/Dockerfile
            args:
                COMMON_NAME: requests
                HTTP_SERVER_PORT: 8082
        restart: unless-stopped
        ports:
            - '8082:8082'
        volumes:
            - ./app/src/Shared:/var/www/src/Shared
            - ./app/src/Requests:/var/www/src/Requests
            - ./app/symfony:/var/www/symfony
            - ./app/config/shared:/var/www/config/shared
            - ./app/config/request:/var/www/config/app
        working_dir: /var/www
        depends_on:
            - db
            - php-fpm-base
            - rabbitmq
    php-fpm-tasks:
        container_name: task_manager-php-tasks
        build:
            context: ./
            dockerfile: ./docker/images/php/Dockerfile
            args:
                COMMON_NAME: tasks
                HTTP_SERVER_PORT: 8083
        restart: unless-stopped
        ports:
            - '8083:8083'
        volumes:
            - ./app/src/Shared:/var/www/src/Shared
            - ./app/src/Tasks:/var/www/src/Tasks
            - ./app/symfony:/var/www/symfony
            - ./app/config/shared:/var/www/config/shared
            - ./app/config/task:/var/www/config/app
        working_dir: /var/www
        depends_on:
            - db
            - php-fpm-base
            - rabbitmq
    db:
        container_name: task_manager-db
        image: postgres:14.2-alpine3.15
        restart: always
        environment:
            POSTGRES_USER: symfony
            POSTGRES_PASSWORD: symfony
        ports:
            - '5432:5432'
        volumes:
            - ./data/db:/var/lib/postgresql/data
            - ./logs/db:/var/log/nginx
    adminer:
        container_name: task_manager-adminer
        image: adminer:latest
        restart: always
        ports:
            - '9080:8080'