doctrine_migrations:
    migrations_paths:
        'App\Shared\Infrastructure\Persistence\Doctrine\Migrations': '%kernel.project_dir%/../src/Shared/Infrastructure/Persistence/Doctrine/Migrations'
        'App\Projections\Infrastructure\Persistence\Doctrine\Migrations': '%kernel.project_dir%/../src/Projections/Infrastructure/Persistence/Doctrine/Migrations'
    enable_profiler: '%kernel.debug%'
