doctrine:
    orm:
        connection: default
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: false
        mappings:
            Projections:
                type: xml
                dir: '%kernel.project_dir%/../src/Projections/Infrastructure/Persistence/Doctrine'
                is_bundle: false
                prefix: App\Projections\Domain\Entity
                alias: Projections