shared_controllers:
    resource: ../src/Shared/Infrastructure/Controller/
    type: attribute

user_controllers:
    resource: ../src/Users/Infrastructure/Controller/
    type: attribute

project_controllers:
    resource: ../src/Projects/Infrastructure/Controller/
    type: attribute

task_controllers:
    resource: ../src/Tasks/Infrastructure/Controller/
    type: attribute

request_controllers:
    resource: ../src/Requests/Infrastructure/Controller/
    type: attribute

kernel:
    resource: ../src/Shared/Infrastructure/Kernel.php
    type: attribute