doctrine:
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: true
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: false
                mappings:
                    Projects:
                        type: xml
                        dir: '%kernel.project_dir%/../src/Projects/Infrastructure/Persistence/Doctrine/Proxy/Mapping'
                        is_bundle: false
                        prefix: App\Projects\Infrastructure\Persistence\Doctrine\Proxy
                        alias: Projects
            read:
                connection: read
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: false
                mappings:
                    Projects:
                        type: xml
                        dir: '%kernel.project_dir%/../src/Projects/Infrastructure/Persistence/Doctrine/Mapping'
                        is_bundle: false
                        prefix: App\Projects\Domain\Entity
                        alias: Projects