doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as Migrations classes should NOT be autoloaded
        'App\Shared\Infrastructure\Persistence\Doctrine\Migrations': '%kernel.project_dir%/src/Shared/Infrastructure/Persistence/Doctrine/Migrations'
        'App\Projects\Infrastructure\Persistence\Doctrine\Migrations': '%kernel.project_dir%/src/Projects/Infrastructure/Persistence/Doctrine/Migrations'
        'App\Users\Infrastructure\Persistence\Doctrine\Migrations': '%kernel.project_dir%/src/Users/Infrastructure/Persistence/Doctrine/Migrations'
        'App\Requests\Infrastructure\Persistence\Doctrine\Migrations': '%kernel.project_dir%/src/Requests/Infrastructure/Persistence/Doctrine/Migrations'
        'App\Tasks\Infrastructure\Persistence\Doctrine\Migrations': '%kernel.project_dir%/src/Tasks/Infrastructure/Persistence/Doctrine/Migrations'
    enable_profiler: '%kernel.debug%'
